const serverUserImage = "http://localhost:8000/userImage";
const serverProjectImage = "http://localhost:8000/projectImage";
const serverOtherImage = "http://localhost:8000/images";

const softSkillOptions = ["Listening", "Negotiation", "Persuasion", "Presentation", "Storytelling", "Nonverbal communication", "Public speaking", "Social skills", "Verbal communication", "Visual communication", "Writing skills", "Reading body language", "Writing reports and proposals", "Adaptability", "Creativity", "Flexibility", "Innovation", "Resourcefulness", "Artistic aptitude", "Critical observation", "Critical thinking", "Design aptitude", "Value education", "Logical thinking", "Problem-solving", "Research skills", "Troubleshooting skills", "Desire to learn", "Thinking outside the box", "Tolerance of change and uncertainty", "Willingness to learn", "Confidence", "Cooperation", "Courtesy", "Energy", "Enthusiasm", "Friendliness", "Honesty", "Humor", "Patience", "Respectability", "Respectfulness", "Delegation", "Leadership", "Management", "Mentoring", "Motivating", "Supervising", "Facilitation", "Conflict management", "Conflict resolution", "Deal-making", "Decision-making", "Dispute resolution", "Inspiring people", "Meeting management", "Project management", "Resolving issues", "Successful coaching", "Talent management ", "Collaboration", "Empathy", "Influence", "Networking", "Persuasion", "Teamwork", "Attentiveness", "Competitiveness", "Dedication", "Dependability", "Independence", "Motivation", "Multitasking", "Organization", "Perseverance", "Persistence", "Planning", "Punctuality", "Reliability", "Resilience", "Scheduling", "Accepting feedback", "Customer service", "Disability awareness", "Diversity awareness", "Emotional intelligence", "Intercultural competence", "Interpersonal skills", "Self-awareness", "Selling skills", "Social skills", "Team building", "Business ethics", "Following direction", "Meeting deadlines", "Results-oriented", "Self-directed", "Self-monitoring", "Self-supervising", "Proper business etiquette", "Staying on task", "Business trend awareness", "Strategic planning", "Time management", "Business ethics", "Business storytelling", "Customer service", "Effective communicator", "Emotion management", "Ergonomic sensitivity", "Follows instructions", "Follows regulations", "Follows rules", "Good attitude", "Highly recommended", "Trainability", "Assertiveness", "Independent", "Interviewing", "Motivating", "Scheduling", "Knowledge management", "Meets deadlines", "Performance management", "Process improvement", "Quick-witted", "Results-oriented", "Safety conscious", "Self-awareness", "Self-supervising", "Stress management", "Willingness to learn"]

const languageOptions = ["Mandarin Chinese", "Spanish", "English", "Hindi", "Bengali", "Portuguese", "Russian", "Japanese", "Yue Chinese", "Vietnamese", "Turkish", "Wu Chinese", "Marathi", "Telugu", "Western Punjabi", "Korean", "Tamil", "Egyptian", "Standard German", "French", "Urdu", "Javanese", "Italian", "Iranian Persian", "Gujarati", "Hausa", "Bhojpuri", "Levantine", "Southern Min"]

const socialMediaOptions = ["YouTube","LinkedIn","Discord","GitHub","Quora","Twitter","Threads","Pinterest","Reddit","stack-overflow","Facebook","Instagram","WhatsApp","Telegram","Snapchat",]

export { serverOtherImage, serverProjectImage, serverUserImage,softSkillOptions,languageOptions ,socialMediaOptions}